# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd12abc9ab6aafe766cec5cab2f653332f62ec264fd703e36d3b9e30dd02a0d511bacf84d5dd2e8a12a013e8ea0c0fedbbfdf7c74f834a3d16dd1c7f07a32996

test:
  secret_key_base: 8203008fc4a19778f6575f8d26a38539148b7f452e77a6238d827d49c0cb066e3dfa3daa47ed2272cec4f4c88ade73977544709fe540e0cca06038ca1b69a6a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
